export const TAURI_COMMANDS = {
  archiveDeal: "archive_deal",
  createUser: "create_user",
  createWmUser: "create_wm_user",
  getWmUserByEmail: "get_wm_user_by_email",
  databaseStatus: "database_status",
  describeDocumentFiles: "describe_document_files",
  extractDealQuestionsAndThesis: "extract_deal_questions_and_thesis",
  exportActivityLog: "export_activity_log",
  getUserByEmail: "get_user_by_email",
  getDeal: "get_deal",
  getDocumentJob: "get_document_job",
  greet: "greet",
  listDealDataRoom: "list_deal_data_room",
  listDeals: "list_deals",
  listSummaryFiles: "list_summary_files",
  loginDemoCommand: "login_demo_command",
  previewDealDocument: "preview_deal_document",
  saveMarkdownSummary: "save_markdown_summary",
  selectSummarySource: "select_summary_source",
  saveDealAndExtract: "save_deal_and_extract",
  searchDocumentChunksKeyword: "search_document_chunks_keyword",
  searchDocumentChunksVector: "search_document_chunks_vector",
  selectDocumentFiles: "select_document_files",
  selectDealDataRoomFolder: "select_deal_data_room_folder",
  startDocumentJobs: "start_document_jobs",
  summarize: "summarize",
  summarizeSelected: "summarize_selected",
  userExistsByEmail: "user_exists_by_email",
} as const;

export type TauriCommandName = (typeof TAURI_COMMANDS)[keyof typeof TAURI_COMMANDS];
